// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "./internal/database/models.js";

export function AddConnection(conn: config$0.Connection): $CancellablePromise<void> {
    return $Call.ByID(2802565916, conn);
}

export function DeleteConnection(id: string): $CancellablePromise<void> {
    return $Call.ByID(3428926502, id);
}

export function ExecuteQuery(connID: string, dbName: string, sql: string): $CancellablePromise<database$0.QueryResult | null> {
    return $Call.ByID(2868660388, connID, dbName, sql).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetColumns(connID: string, dbName: string, table: string): $CancellablePromise<database$0.ColumnInfo[]> {
    return $Call.ByID(280215594, connID, dbName, table).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetConnections(): $CancellablePromise<config$0.Connection[]> {
    return $Call.ByID(1541859132).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetDatabases(connID: string): $CancellablePromise<string[]> {
    return $Call.ByID(2970679019, connID).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetTables(connID: string, dbName: string): $CancellablePromise<string[]> {
    return $Call.ByID(3495117462, connID, dbName).then(($result: any) => {
        return $$createType6($result);
    });
}

export function TestConnection(conn: config$0.Connection): $CancellablePromise<void> {
    return $Call.ByID(1257240193, conn);
}

export function UpdateConnection(conn: config$0.Connection): $CancellablePromise<void> {
    return $Call.ByID(619964812, conn);
}

// Private type creation functions
const $$createType0 = database$0.QueryResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = database$0.ColumnInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = config$0.Connection.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Array($Create.Any);
