// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ColumnInfo {
    "name": string;
    "type": string;
    "nullable": string;
    "key": string;
    "default": string;
    "extra": string;

    /** Creates a new ColumnInfo instance. */
    constructor($$source: Partial<ColumnInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("nullable" in $$source)) {
            this["nullable"] = "";
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("default" in $$source)) {
            this["default"] = "";
        }
        if (!("extra" in $$source)) {
            this["extra"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ColumnInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnInfo($$parsedSource as Partial<ColumnInfo>);
    }
}

export class QueryResult {
    "columns": string[];
    "rows": string[][];
    "error": string;

    /**
     * milliseconds
     */
    "duration": number;

    /** Creates a new QueryResult instance. */
    constructor($$source: Partial<QueryResult> = {}) {
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryResult instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryResult {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField1_0($$parsedSource["rows"]);
        }
        return new QueryResult($$parsedSource as Partial<QueryResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($$createType0);
